version: '3.8'
services:
  portfolio:
    build: .
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src # Pour le hot-reload si tu configures le dev server, sinon juste pour le build
    restart: always
    